name: Main
on: [push, pull_request]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      - run: vercel --no-clipboard --scope ${{secrets.VERCEL_SCOPE}} --token=${{secrets.VERCEL_TOKEN}}
        env: 
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
        id: 'abc'
      - run: echo ${{abc.outputs}}