on:
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run lint
      - run: npm run check
      - id: preview
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npm run -s deploy:preview
      - env:
          PREVIEW_URL: ${{ steps.preview.outputs.stdout }}
        run: echo $PREVIEW_URL
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: test-results
