on: 
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      - id: preview
        run: npm run -s deploy:preview
      - env: 
          PREVIEW_URL: ${{ steps.preview.outputs.stdout }}
        run: npm run e2e
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: test-results